### ISSUE TITLE
sublime-settings file

### ISSUE THREAD

**Issue by blandfbt** [blandfbt/PPCL#9]
The sublime settings file for PPCL that ships with this package does not seem to properly load in the users' environment. This affects the word endings parameter for word stops.

**Comment by semiamaurotic** [comment]
I've noticed the settings files won't load from the menu either. I believe this because the package name, as installed through Package Control, is actually "PPCL Language Syntax and Editor." So, line 112  in 
"Main.sublime-menu": 

`"file": "${packages}/PPCL/ppcl.sublime-settings"`

Should probably be:

`"file": "${packages}/PPCL Language Syntax and Editor/ppcl.sublime-settings"`

**Comment by blandfbt** [comment]
great, i'll dig into that.  i think you're probably right.
